{% set name = "aws-crt-cpp" %}
{% set version = "0.17.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4e3be5f2cd261986b9c27b35fd5ce04fc61d79e6ea8a653791c14f721657f47d

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-crt-cpp", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
  host:
    - aws-c-auth
    - aws-c-cal
    - aws-c-common
    - aws-c-event-stream
    - aws-c-http
    - aws-c-io
    - aws-c-mqtt
    - aws-checksums
    - aws-c-s3

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-io${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/io/io.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\io\\io.h exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-io.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-crt-cpp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C++ wrapper around the aws-c-* libraries. Provides Cross-Platform Transport Protocols and SSL/TLS implementations for C++.

extra:
  recipe-maintainers:
    - xhochy
